[package]
name = "ws-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
warp = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

base64 = "0.22"
web-push = "0.10"
